In [47]:
import numpy as np
from numpy.random import randn

In [46]:
# Create ndarray, pass a list objects into the array() method 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 


In [19]:
# Creates an array of specified shape(7,4) 
#and fills it with random values as per standard normal distribution.
data = randn(7, 4) 

array([[ 0.45458939, -0.45934074, -0.58018593,  0.32799179],
       [-0.59585869, -0.60380541, -0.07232276,  0.81464442],
       [-2.83281838,  0.86558939, -0.06453426, -2.24688031],
       [-0.6189538 ,  1.03881246, -0.15386808,  0.9265009 ],
       [-1.19842156, -0.48208815, -1.13004477,  1.78282575],
       [ 1.24971655,  0.99225303,  0.28732829, -1.7132989 ],
       [ 0.95578037,  0.66493227, -0.60896727,  0.67895099]])

In [20]:
# Recall variable 'names' before.
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [25]:
# Recall variable 'data' before.
data

array([[ 0.45458939, -0.45934074, -0.58018593,  0.32799179],
       [-0.59585869, -0.60380541, -0.07232276,  0.81464442],
       [-2.83281838,  0.86558939, -0.06453426, -2.24688031],
       [-0.6189538 ,  1.03881246, -0.15386808,  0.9265009 ],
       [-1.19842156, -0.48208815, -1.13004477,  1.78282575],
       [ 1.24971655,  0.99225303,  0.28732829, -1.7132989 ],
       [ 0.95578037,  0.66493227, -0.60896727,  0.67895099]])

In [24]:
# Comparing names with the string 'Bob' yields a boolean array.
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [26]:
#The same as: data[[True, False, False, True, False, False, False]]
#and this just means to get row 0 and row 4 from data.
data[names == 'Bob']

array([[ 0.45458939, -0.45934074, -0.58018593,  0.32799179],
       [-0.6189538 ,  1.03881246, -0.15386808,  0.9265009 ]])

In [27]:
# Gives the same rows, but now restricts the columns to start with column 2. 
data[names == 'Bob', 2:]

array([[-0.58018593,  0.32799179],
       [-0.15386808,  0.9265009 ]])

In [28]:
# Before the comma concerns the rows, after the comma concerns the columns.
data[names == 'Bob', 3]

array([0.32799179, 0.9265009 ])

In [31]:
# Comparing names with the string 'Bob' yields a boolean array.
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [34]:
# The same as: data[[False,  True,  True, False,  True,  True,  True]]
#and this just means to get row 1,2,4,5 and row 6 from data.
data[~(names == 'Bob')]

array([[-0.59585869, -0.60380541, -0.07232276,  0.81464442],
       [-2.83281838,  0.86558939, -0.06453426, -2.24688031],
       [-1.19842156, -0.48208815, -1.13004477,  1.78282575],
       [ 1.24971655,  0.99225303,  0.28732829, -1.7132989 ],
       [ 0.95578037,  0.66493227, -0.60896727,  0.67895099]])

In [37]:
# Combine multiple boolean conditions, names with the string 'Bob' or names with the string 'Will'.
mask = (names == 'Bob') | (names == 'Will')

In [39]:
# Recall variable 'mask' before
mask

array([ True, False,  True,  True,  True, False, False])

In [40]:
# The same as: data[[ True, False,  True,  True,  True, False, False]]
data[mask]

array([[ 0.45458939, -0.45934074, -0.58018593,  0.32799179],
       [-2.83281838,  0.86558939, -0.06453426, -2.24688031],
       [-0.6189538 ,  1.03881246, -0.15386808,  0.9265009 ],
       [-1.19842156, -0.48208815, -1.13004477,  1.78282575]])

In [41]:
# Set all of the negative values in data to 0
data[data < 0] = 0

In [42]:
# Recall variable 'data' before
data

array([[0.45458939, 0.        , 0.        , 0.32799179],
       [0.        , 0.        , 0.        , 0.81464442],
       [0.        , 0.86558939, 0.        , 0.        ],
       [0.        , 1.03881246, 0.        , 0.9265009 ],
       [0.        , 0.        , 0.        , 1.78282575],
       [1.24971655, 0.99225303, 0.28732829, 0.        ],
       [0.95578037, 0.66493227, 0.        , 0.67895099]])

In [43]:
# Set all of the different values 'Joe' in data to 7
data[names != 'Joe'] = 7

In [44]:
# Recall variable 'data' before
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.81464442],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.24971655, 0.99225303, 0.28732829, 0.        ],
       [0.95578037, 0.66493227, 0.        , 0.67895099]])